export const SET_CURRENT_PROJECT_ID = Symbol('SET_CURRENT_PROJECT_ID');
export const SET_CURRENT_PROJECT_RECT = Symbol('SET_CURRENT_PROJECT_RECT');
export const CLEAR_CURRENT_PROJECT = Symbol('CLEAR_CURRENT_PROJECT');
